#!/bin/bash
#
# To register to service ..
#
# sudo cp hatio-node-script /etc/init.d/
# sudo chmod 755 /etc/init.d/hatio-node-script
# sudo chown root:root /etc/init.d/hatio-node-script
# Then you need to register it to run at startup.
#
# sudo update-rc.d hatio-node-script defaults

start() {
    export NVM_DIR="/home/pi/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

    nohup node /home/pi/mynode/firebase-node.js > /dev/null 2> /dev/null &
    nohup node /home/pi/mynode/discovery-net.js > /dev/null 2> /dev/null &
}

case "$1" in
  start)
    start
    ;;
  stop)
    ;;
  status)
    ;;
  restart|reload|condrestart)
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|reload|status}"
    exit 1
esac    

exit 0
